trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: OMF_to_OCS_Quick_Start_Jupyter_Python

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    variables:
      - name: ClientId
        value: $(OMFQuickStartClientId)
      - name: ClientSecret
        value: $(OMFQuickStartClientSecret)
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'OMFQuickStartClientId, OMFQuickStartClientSecret, TopicName, SubscriptionName, TenantId, NamespaceId, Resource'

      - script: |
          echo Install pip
          call python -m pip install --upgrade pip
          echo Install tools
          call pip install nbconvert
          call pip install requests
          call pip install unittest
          call pip install pytest
          echo Install requirements
          call pip install -r requirements.txt
          echo Run tests
          call jupyter nbconvert --to script quickstart.ipynb
          python -m pytest --junitxml=junit/test-results.xml ./quickstart.py
          echo Complete
        displayName: 'Run tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-*.xml'
          searchFolder: '$(Build.SourcesDirectory)'
          failTaskOnFailedTests: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Publish test results'
        condition: always()

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      buildSteps:
        - script: |
            pip install nbconvert
            jupyter nbconvert --to script quickstart.ipynb
      skipPolaris: true
      useRequirementsTxt: true
